# Generated by Django 6.0 on 2025-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_id_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
